/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankdummyserver;

import com.asac.function.impl.BERTLV_Impl;
import com.asac.test.ABDServer;
import com.function.StringFunction;
import com.muamalat.iso8583.PackagerFactory;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jpos.iso.ISOException;
import org.jpos.iso.ISOMsg;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author herrysuganda
 */
public class MainSimmulator extends javax.swing.JFrame {

    /**
     * Creates new form MainSimmulator
     */
    public MainSimmulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtiso = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtRef = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtorderid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtproduct = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtiso2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtxml = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtStressTest = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtSessionid = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        txtCB = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        txtBit48 = new javax.swing.JTextField();
        txtBit63 = new javax.swing.JTextField();
        txtBit103 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Send Bill Inquiry to SGO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtRef.setText("1");

        jButton2.setText("Send Bill Payment to SGO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Send Bill Inquiry to Verdana");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Send Bill Payment to Verdana");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("STAN");

        txtorderid.setText("081286224918");
        txtorderid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtorderidActionPerformed(evt);
            }
        });

        jLabel2.setText("Customer Number (C3)");

        txtamount.setText("2500000");

        jLabel3.setText("Amount");

        txtproduct.setText("777777");
        txtproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductActionPerformed(evt);
            }
        });

        jLabel4.setText("Produc Code (C4)");

        jLabel5.setText("ISO Message");

        txtiso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiso2ActionPerformed(evt);
            }
        });

        jButton8.setText("Send ISO Msg SGO");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel6.setText("XML Request");

        jButton6.setText("Send To BPJS");

        jButton7.setText("Send Inquiry BPJS to Verdana");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setText("Send Payment BPJS to Verdana");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel7.setText("Stress Test");

        txtStressTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStressTestActionPerformed(evt);
            }
        });

        jButton10.setText("Stress Test Bill Inquiry to Verdana");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel8.setText("Session Id (C5)");

        txtSessionid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSessionidActionPerformed(evt);
            }
        });

        jButton11.setText("Send Bill Inquiry to MKM");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Send Bill Payment to MKM");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        txtCB.setText("0");

        jLabel9.setText("CB");

        jButton13.setText("Reset Dummy Multifinance Verdana");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Reset Dummy PDAM Verdana");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Bill Inquiry Sumsel");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Bill Payment Sumsel");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton5.setText("signon");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton17.setText("Bill Inquiry Bali");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Bill Payment Bali");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("Test MSG JATIM");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("Payment Advice to MKM");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("BRIS TOPUP");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setText("Send Bill Inquiry to WAY4");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("Send payment to WAY4");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtisoLayout = new javax.swing.GroupLayout(txtiso);
        txtiso.setLayout(txtisoLayout);
        txtisoLayout.setHorizontalGroup(
            txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtisoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtisoLayout.createSequentialGroup()
                        .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(txtisoLayout.createSequentialGroup()
                                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(txtisoLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtxml))
                                    .addComponent(jButton6)
                                    .addGroup(txtisoLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtStressTest, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 506, Short.MAX_VALUE))
                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(txtisoLayout.createSequentialGroup()
                        .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(txtisoLayout.createSequentialGroup()
                                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCB)
                            .addComponent(txtproduct)
                            .addComponent(txtRef)
                            .addComponent(txtorderid)
                            .addComponent(txtamount)
                            .addComponent(txtiso2)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSessionid)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtisoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtisoLayout.createSequentialGroup()
                                        .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())))
                            .addGroup(txtisoLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtBit103)
                                        .addComponent(txtBit48)
                                        .addComponent(txtBit63, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                        .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );
        txtisoLayout.setVerticalGroup(
            txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtisoLayout.createSequentialGroup()
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtisoLayout.createSequentialGroup()
                        .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtorderid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(txtisoLayout.createSequentialGroup()
                        .addComponent(jButton22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtisoLayout.createSequentialGroup()
                        .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtiso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtSessionid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(txtisoLayout.createSequentialGroup()
                        .addComponent(txtBit48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBit63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBit103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton15)
                    .addComponent(jButton17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton16)
                    .addComponent(jButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton7)
                    .addComponent(jButton19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton9)
                        .addComponent(jButton21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(jButton20))
                .addGap(48, 48, 48)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14)
                .addGap(52, 52, 52)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtxml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtStressTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtiso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("0100");
            msg.set(3, "280000");
            msg.set(4, txtamount.getText().trim());
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(11, txtRef.getText());
            msg.set(18, "6010");
            msg.set(32, "000147");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", txtorderid.getText().trim());
            tlvdata.put("C4", txtproduct.getText().trim());
            tlvdata.put("C5", txtSessionid.getText().trim());
            tlvdata.put("CB", txtCB.getText().trim());
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("9700");
            msg.set(3, "380000");
            msg.set(4, txtamount.getText().trim());
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(11, txtRef.getText());
            msg.set(32, "000147");
            msg.set(18, "6010");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", txtorderid.getText().trim());
            tlvdata.put("C4", txtproduct.getText().trim());
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int jmlloop = Integer.valueOf(txtStressTest.getText());
        JOptionPane.showMessageDialog(null, new Date());
        try {
            // TODO add your handling code here:
            for (int i = 0; i < jmlloop; i++) {
                ISOMsg msg = new ISOMsg();
                msg.setPackager(PackagerFactory.getPackager());
                msg.setMTI("0200");
                msg.set(3, "380000");
                msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
                msg.set(12, StringFunction.getCurrentTimeHHmmsss());
                msg.set(13, StringFunction.getCurrentDateMMDD());
                msg.set(11, txtRef.getText());
                msg.set(37, StringFunction.pad("101" + txtRef.getText(), 12, "0", "Right"));
                HashMap tlvdata = new HashMap();
                tlvdata.put("C1", "001");
                tlvdata.put("C3", txtorderid.getText().trim());
                tlvdata.put("C4", txtproduct.getText().trim());
                tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
                msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
                ABDServer.getInstance().sendMessage(new String(msg.pack()));
                txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
            }
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txtStressTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStressTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStressTestActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("0100");
            msg.set(3, "280000");
            msg.set(4, txtamount.getText().trim());
            
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(11, txtRef.getText());
            msg.set(32, "000147");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", txtorderid.getText().trim());
            tlvdata.put("CC", txtSessionid.getText().trim());
            tlvdata.put("CB", txtCB.getText().trim());
//            tlvdata.put("CC", txtCB.getText().trim());

            tlvdata.put("C4", txtproduct.getText().trim());
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("9700");
            msg.set(3, "380000");
            msg.set(4, txtamount.getText().trim());
            
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(11, txtRef.getText());
            msg.set(32, "000147");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", txtorderid.getText().trim());
            tlvdata.put("CC", txtCB.getText().trim());
            tlvdata.put("C4", txtproduct.getText().trim());
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        ABDServer.getInstance().sendMessage(txtiso2.getText().trim());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtiso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtiso2ActionPerformed

    private void txtproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductActionPerformed

    private void txtorderidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtorderidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorderidActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("0100");
            msg.set(3, "280000");
            msg.set(4, txtamount.getText());
            
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(11, txtRef.getText());
            msg.set(32, "000147");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", txtorderid.getText().trim());
            tlvdata.put("C4", txtproduct.getText().trim());
            tlvdata.put("C5", txtSessionid.getText().trim());
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("9700");
            msg.set(3, "380000");
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(11, txtRef.getText());
            msg.set(32, "000147");
            msg.set(37, StringFunction.pad("101" + txtRef.getText(), 12, "0", "Right"));
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", txtorderid.getText().trim());
            tlvdata.put("C4", txtproduct.getText().trim());
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("0100");
            msg.set(3, "280000");
            msg.set(4, txtamount.getText().trim());
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(11, txtRef.getText());
            msg.set(32, "000147");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", txtorderid.getText().trim());
            tlvdata.put("C4", txtproduct.getText().trim());
            tlvdata.put("C5", txtSessionid.getText().trim());
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("9700");
            msg.set(3, "380000");
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(11, txtRef.getText());
            msg.set(32, "000147");
            msg.set(41, "99900147");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
//            msg.set(37, "000123000123");
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", txtorderid.getText().trim());
            tlvdata.put("C4", txtproduct.getText().trim());
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("9700");
            msg.set(3, "380000");
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(11, txtRef.getText());
            msg.set(32, "000147");
            msg.set(37, StringFunction.pad("101" + txtRef.getText(), 12, "0", "Right"));
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", "111111111111");
            tlvdata.put("C4", "005006");
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("9700");
            msg.set(3, "380000");
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(11, txtRef.getText());
            msg.set(32, "000147");
            msg.set(37, StringFunction.pad("101" + txtRef.getText(), 12, "0", "Right"));
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", "000099999");
            tlvdata.put("C4", "002039");
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("0200");
            msg.set(3, "380000");
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(11, txtRef.getText());
            msg.set(32, "0147");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            msg.set(121, "123");
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", txtorderid.getText().trim());
            tlvdata.put("C4", txtproduct.getText().trim());
            tlvdata.put("CB", txtCB.getText().trim());
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("0200");
            msg.set(3, "280000");
            msg.set(4, txtamount.getText());
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(11, txtRef.getText());
            msg.set(32, "0147");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", txtorderid.getText().trim());
            tlvdata.put("C4", txtproduct.getText().trim());
            tlvdata.put("C5", txtSessionid.getText().trim());
            tlvdata.put("CB", txtCB.getText().trim());//tlvdata.put("CB", txtCB.getText().trim() + "|04|05|2016|123456789012345");
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
//        String msgHexa = "60608300080110303801000EC1040431100000000000000020046110200009010008373130353932323030343631323030343631303031343731303539323134373130353932313233343536370042373734303030343132360D0A4D617277616E2050726979616E6120202020202020202020202020202020002030303030303030303043373030353038323535360006323030303639";

        try {
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("0800");
            msg.set(7, "0416034949");
            msg.set(11, "232253");
            msg.set(70, "001");
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("9700");
            msg.set(3, "380000");
            //msg.set(2, "0008881234567894");
            msg.set(2, "011012991234123");
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(14, StringFunction.getCurrentDateYYMM());
            msg.set(11, txtRef.getText());
            msg.set(18, "6010");
            msg.set(32, "129");
            msg.set(52, "000000");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", txtorderid.getText().trim());
            tlvdata.put("C4", txtproduct.getText().trim());
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
        

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("0100");
            msg.set(2, "0008881234567894");
            msg.set(3, "280000");
            msg.set(4, txtamount.getText().trim());
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(14, StringFunction.getCurrentDateYYMM());
            msg.set(11, txtRef.getText());
            msg.set(18, "6010");
            msg.set(32, "129");
            msg.set(52, "123456");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", txtorderid.getText().trim());
            tlvdata.put("C4", txtproduct.getText().trim());
            tlvdata.put("C5", txtSessionid.getText().trim());
            tlvdata.put("CB", txtCB.getText().trim());
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));

    }//GEN-LAST:event_jButton18ActionPerformed

    private void txtSessionidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSessionidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSessionidActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("9700");
            msg.set(2, "0001140322825641");
            msg.set(3, "380000");
            msg.set(4, "000000000000");
            msg.set(7, "0927113409");
            msg.set(11, "113409");
            msg.set(32, "000777");
            msg.set(37, "474947249331");
//            msg.set(39, "82");
            msg.set(41, "90001000");
            msg.set(47, "945009GatewayCD");
            msg.set(49, "360");
            msg.set(103, "0322825641");
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
        

    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("0420");
            msg.set(3, "280000");
            msg.set(4, txtamount.getText().trim());
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(11, txtRef.getText());
            msg.set(18, "6010");
            msg.set(32, "000147");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", txtorderid.getText().trim());
            tlvdata.put("C4", txtproduct.getText().trim());
            tlvdata.put("C5", txtSessionid.getText().trim());
            tlvdata.put("CB", txtCB.getText().trim());
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));

    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        try {
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("0200");
//            msg.set(2, "0008881234567894");
            msg.set(3, "280000");
            msg.set(4, txtamount.getText().trim());
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(14, StringFunction.getCurrentDateYYMM());
            msg.set(11, txtRef.getText());
            msg.set(18, "6010");
//            msg.set(102, "081286224918");
//            msg.set(32, "129");
//            msg.set(52, "123456");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            HashMap tlvdata = new HashMap();
            tlvdata.put("C1", "001");
            tlvdata.put("C3", txtorderid.getText().trim());
            tlvdata.put("C4", txtproduct.getText().trim());
            tlvdata.put("C5", txtSessionid.getText().trim());
            tlvdata.put("CB", txtCB.getText().trim());
            tlvdata.put("C9", StringFunction.pad(txtRef.getText(), 6, "0", "Right"));
            msg.set(112, new BERTLV_Impl().generateBertlv2(tlvdata));
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
        

    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            
            msg.setMTI("0200");
            msg.set(2, "5221840063046552");
            msg.set(3, "391000");
            msg.set(4, "001053399500");
            msg.set(7, "0412055749");
//            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(11, "028619");
            msg.set(12, "125749");
//            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, "0412");
//            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(15, "0412");
            msg.set(18, "6017");
            msg.set(22, "011");
            msg.set(25, "00");
            msg.set(32, "2");
            msg.set(35, "5221840063046552=24002");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            msg.set(41, "00001902");
            msg.set(42, "300157273308508");
            msg.set(43, "BRI ATM BERSAMA SIMULATOR               ");
            msg.set(48, "                              88                                            ");
            msg.set(49, "360");
            msg.set(52, "D844098FE22408C9");
            msg.set(100, "002");
            msg.set(102, "");
            msg.set(103, "8072030000000002");
            msg.set(125, "3");
            msg.set(127, "147");
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());

            //gopay mobile pay
            msg.setMTI("0200");
            msg.set(2, "6019233300000649");
            msg.set(3, "001000");
            msg.set(4, "000001200000");
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(11, "881203");
            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
            msg.set(13, StringFunction.getCurrentDateMMDD());
            msg.set(14, "9912");
            msg.set(18, "6017");
            msg.set(32, "0147");
            msg.set(35, "6019233300000649D9912");
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            msg.set(41, "525");
            msg.set(42, "MBANKING");
            msg.set(43, "MBANKING");
            //            msg.set(48, "81012881012801            120191011131754GOJEK USER                    000000010000000000002000                    ");
            msg.set(48, txtBit48.getText());
            msg.set(49, "360");
            msg.set(52, "370B597B0C100A7B");
            //            msg.set(63, "524");
            msg.set(63, txtBit63.getText());
            msg.set(102, "3300000649");
            //            msg.set(103, "81012801");
            msg.set(103, txtBit103.getText());
            msg.set(125, "2");
            msg.set(127, "0147");
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
    }//GEN-LAST:event_jButton23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSimmulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSimmulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSimmulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSimmulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSimmulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBit103;
    private javax.swing.JTextField txtBit48;
    private javax.swing.JTextField txtBit63;
    private javax.swing.JTextField txtCB;
    private javax.swing.JTextField txtRef;
    private javax.swing.JTextField txtSessionid;
    private javax.swing.JTextField txtStressTest;
    private javax.swing.JTextField txtamount;
    private javax.swing.JPanel txtiso;
    private javax.swing.JTextField txtiso2;
    private javax.swing.JTextField txtorderid;
    private javax.swing.JTextField txtproduct;
    private javax.swing.JTextField txtxml;
    // End of variables declaration//GEN-END:variables
}
